server:
  port: 8090

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 15672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: BookListner
  exchange:
    name: BookExchange
    routingkey: rabbitmqkey01

