spring:
  profiles:
    active: local
---
spring:
  application:
    name: Book-Service

server:
  port: 8090

---
spring:
  profiles: local

eureka:
  instance:
    preerIpAddress: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

