spring:
  profiles:
    active: local
---
spring:
  application:
    name: Book-Service

server:
  port: 8090

---
spring:
  profiles: local
  boot:
    admin:
      client:
        url: http://localhost:8090
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    preerIpAddress: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

