server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tamal2401/Java-Series
          cloneOnStart: true

management:
  security:
    enabled: false