spring:
  profiles:
    active: local, gatekeeper
---
spring:
  application:
    name: Eureka-Server

server:
  port: ${vcap.application.port:8761}

---
spring:
  profiles: local

eureka:
  server:
    enableSelfPreservation: false
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles: cloud

eureka:
  server:
    enableSelfPreservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: gatekeeper

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env, beans, configprops, threaddump, heapdump'
  endpoint:
    health:
      show-details: always
