spring:
  profiles:
    active: local
---
spring:
  application:
    name: Eureka-Server

server:
  port: ${vcap.application.port:8761}

---
spring:
  profiles: local

eureka:
  server:
    enableSelfPreservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: cloud

eureka:
  server:
    enableSelfPreservation: false
  client:
    register-with-eureka: false
    fetch-registry: false


