server:
  port: 8091
eureka:
  client:
    service-url: http://localhost:8090/eureka
spring:
  boot:
    admin:
      url: http://localhost:8093
      username: admin
      password: admin
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017