server:
  port: 8091
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
#spring:
#  boot:
#    admin:
#      url: http://localhost:8093
#      username: admin
#      password: admin

