spring:
  application:
    name: spring MFA
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: onlyjohn98@gmail.com
    password: keepitsimple1994!
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9000
