server:
  port: 8091
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
#spring:
#  boot:
#    admin:
#      url: http://localhost:8093
#      username: admin
#      password: admin

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic

employee:
  management:
    roles:
      - Developer
      - QA
      - Scrum Master
      - PO
      - Team Lead
      - PM
    designations:
      associate:
        - Developer
        - QA
      analyst:
        - Developer
        - QA
      consultant:
        - Developer
        - QA
        - Scrum Master
      senior_consultant:
        - Scrum Master
        - PO
        - Team Lead
      manager:
        - PO
        - PM