server:
  port: 8081

#spring:
#  boot:
#    admin:
#      url: http://localhost:8093
#      username: admin
#      password: admin
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true