spring:
  profiles:
    active: local
---
spring:
  application:
    name: spring-admin

server:
  port: 8070

---
spring:
  profiles: local
  boot:
    admin:
      client:
        url: http://localhost:8090
        username: admin
        password: admin

eureka:
  instance:
    preerIpAddress: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
