spring:
  profiles:
    active: local
---
spring:
  application:
    name: Zuul-Proxy

server:
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    legacy:
      path: /**

ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: local

eureka:
  instance:
    preerIpAddress: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
